image: python:3.7

definitions:
  steps:
    - step: &build-upload
        caches:
          - pip
        script:
          - pip install twine
          - python setup.py bdist_wheel sdist
          - twine upload --skip-existing --reposity-url https://test.pypi.org/legacy/ -u $PYPI_USER -p $PYPI_PASS dist/*

pipelines:
  default:
    - parallel:
      - step: *build-upload
      - step:
          <<: *build-upload
          image: python:3.8
      - step:
          <<: *build-upload
          image: python:3.6