pipelines:
  default:
    - parallel:
      - step:
          image: quay.io/pypa/manylinux2010_x86_64
          caches:
            - pip
          script:
            - for py in 27 36 37 38; do echo building Python${py} wheel; for pip in /opt/python/cp${py}*/bin/pip; do $pip wheel .; done; done
            - auditwheel repair *.whl -w wheelhouse
            - pip install twine
            - twine upload --skip-existing --reposity-url https://test.pypi.org/legacy/ -u $PYPI_USER -p $PYPI_PASS wheelhouse/*
      - step:
          image: quay.io/pypa/manylinux2010_i686
          caches:
            - pip
          script:
            - for py in 27 36 37 38; do echo building Python${py} wheel; for pip in /opt/python/cp${py}*/bin/pip; do linux32 $pip wheel .; done; done
            - auditwheel repair *.whl -w wheelhouse
            - pip install twine
            - twine upload --skip-existing --reposity-url https://test.pypi.org/legacy/ -u $PYPI_USER -p $PYPI_PASS wheelhouse/*